### ISSUE TITLE
Build failures on i386

### ISSUE THREAD

**Issue by Sp1l** [icing/mod_tls#6]
The FreeBSD build infrastructure is reporting errors on i386 builds.

* [FreeBSD 14.1](https://pkg-status.freebsd.org/beefy21/data/141i386-default/68d58a0fbe72/logs/ap24-mod_tls-0.14.0.log)
* [FreeBSD 13.4](https://pkg-status.freebsd.org/beefy15/data/134i386-default/68d58a0fbe72/logs/ap24-mod_tls-0.14.0.log)

Previously, the mod_tls module was disabled by default in the www/apache24 port.
I'm not testing i386 any longer when releasing as it's no longer a tier-1 architecture for FreeBSD.

Any hints?
(Now working on the RusTLS 0.14.1 upgrade)

**Comment by Sp1l** [comment]
Building against rustls 0.14.1 works fine on amd64.

Is that a supported build? README.md says "rustls-ffi v0.14.0"

**Comment by cpu** [comment]
There were no API/ABI changes between rustls-ffi 0.14.0 and 0.14.1 so the two should be equivalent AFAIK. The .1 release only bumped the internal rustls dependency.

**Comment by cpu** [comment]
The relevant error appears to be:
```
tls_cache.c:244:25: error: implicit conversion changes signedness: 'unsigned int' to 'apr_ssize_t' (aka 'int') [-Werror,-Wsign-conversion]
  244 |         apr_ssize_t n = klen;
      |                     ~   ^~~~
1 error generated.
```

* `key` here is a [`const rustls_slice_bytes *`](https://ffi.rustls.dev/#rustls-slice-bytes) so `len` is `size_t`.
* `unsigned int klen` is initialized from `(unsigned int) key->len`, and the `(unsigned int)` cast is required for use with the [`ap_socache_provider_t`](https://nightlies.apache.org/httpd/trunk/doxygen/structap__socache__provider__t.html) APIs (`retrieve` and `remove` in particular).
* The implicit conversion to `apr_ssize_t` flagged by the i386 build is required to create an arg for [`apr_hashfunc_default()`](https://nightlies.apache.org/httpd/trunk/doxygen/group__apr__hash.html#ga8baa6e9d9d6c2c496d2a0ff1a5c53abe). 

So from my perspective it seems like the `tls_cache.c` code should verify that both casts are within range of the respective types, and then make the `apr_ssize_t` cast explicit so it works as expected on platforms where the type is a signed `int`.

<details>
<summary>Perhaps a diff along these lines?</summary>

```diff
diff --git a/src/tls_cache.c b/src/tls_cache.c
index 5fc874f..333fd67 100644
--- a/src/tls_cache.c
+++ b/src/tls_cache.c
@@ -228,12 +228,17 @@ static rustls_result tls_cache_get(
     tls_conf_conn_t *cc = tls_conf_conn_get(c);
     tls_conf_server_t *sc = tls_conf_server_get(cc->server);
     apr_status_t rv = APR_ENOENT;
     unsigned int vlen, klen;
     const unsigned char *kdata;
 
     if (!sc->global->session_cache) goto not_found;
     tls_cache_lock(sc->global);
 
+    if (key->len > UINT_MAX || key->len > SSIZE_MAX) {
+       return RUSTLS_RESULT_INVALID_PARAMETER;
+    }
+
     kdata = key->data;
     klen = (unsigned int)key->len;
     vlen = (unsigned int)count;
@@ -241,7 +246,7 @@ static rustls_result tls_cache_get(
         sc->global->session_cache, cc->server, kdata, klen, buf, &vlen, c->pool);
 
     if (APLOGctrace4(c)) {
-        apr_ssize_t n = klen;
+        apr_ssize_t n = (apr_ssize_t) klen;
         ap_log_cerror(APLOG_MARK, APLOG_TRACE4, rv, c, "retrieve key %d[%8x], found %d val",
             klen, apr_hashfunc_default((const char*)kdata, &n), vlen);
     }
```
</details>

@icing would appreciate your input on ^ as someone much better versed in the nuance of C data type conversions and the APR.

**Comment by icing** [comment]
This looks correct. While the SSIZE_MAX check is only relevant for the trace output, we need to assure that the size_t value fits into the unsigned int that the apache provider works with.

**Comment by cpu** [comment]
> This looks correct. While the SSIZE_MAX check is only relevant for the trace output, we need to assure that the size_t value fits into the unsigned int that the apache provider works with.

Great, thanks! I will open a PR in a little bit. I'd like to try a full i386 build first to make sure there aren't any other lurking issues.

**Comment by cpu** [comment]
>  I will open a PR in a little bit. 

Done: https://github.com/icing/mod_tls/issues/7

**Comment by icing** [comment]
Fixed in 0343e64fe860000019d3fe0de6f4f202eed29afa. Thanks!
